services:
  anvil:
    platform: linux/amd64
    build:
      context: ./docker/anvil
      dockerfile: Dockerfile.anvil
    env_file:
      - .env
    ports:
      - "8545:8545"

  registration:
    platform: linux/amd64
    build:
      context: ./docker/registration
      dockerfile: Dockerfile.registration
    depends_on:
      - anvil
    env_file:
      - .env
    volumes:
      - ./.eigenlayer:/root/.eigenlayer
  node1:
    image: opacitylabs/opacity-avs-node:local
    environment:
      - OPERATOR_BLS_KEY_PASSWORD=Testacc1Testacc1
      - OPERATOR_BLS_KEY_FILE=/.eigenlayer/operator_keys/testacc1.bls.key.json        
    volumes:
      - ./.eigenlayer/operator_keys/testacc1.bls.key.json:/opacity-avs-node//opacity.bls.key.local.json
      - ./docker/node/opacity.config.yaml:/opacity-avs-node/config/opacity.config.yaml
      - ./docker/node/config.yaml:/opacity-avs-node/config/config.yaml
    ports:
      - "7047:7047"
    depends_on:
      registration: 
        condition: service_completed_successfully
  node2:
    image: opacitylabs/opacity-avs-node:local
    environment:
      - OPERATOR_BLS_KEY_PASSWORD=Testacc1Testacc1
      - OPERATOR_BLS_KEY_FILE=/.eigenlayer/operator_keys/testacc2.bls.key.json        
    volumes:
      - ./.eigenlayer/operator_keys/testacc2.bls.key.json:/opacity-avs-node//opacity.bls.key.local.json
      - ./docker/node/opacity.config.yaml:/opacity-avs-node/config/opacity.config.yaml
      - ./docker/node/config.yaml:/opacity-avs-node/config/config.yaml
    ports:
      - "7048:7047"
    depends_on:
      registration: 
        condition: service_completed_successfully
  node3:
    image: opacitylabs/opacity-avs-node:local
    environment:
      - OPERATOR_BLS_KEY_PASSWORD=Testacc1Testacc1
      - OPERATOR_BLS_KEY_FILE=/.eigenlayer/operator_keys/testacc3.bls.key.json        
    volumes:
      - ./.eigenlayer/operator_keys/testacc3.bls.key.json:/opacity-avs-node//opacity.bls.key.local.json
      - ./docker/node/opacity.config.yaml:/opacity-avs-node/config/opacity.config.yaml
      - ./docker/node/config.yaml:/opacity-avs-node/config/config.yaml
    ports:
      - "7049:7047"
    depends_on:
      registration: 
        condition: service_completed_successfully
