services:
  ethereum:
    platform: linux/amd64
    build:
      context: ./docker/ethereum
      dockerfile: Dockerfile.ethereum
    env_file:
      - .env
    ports:
      - "8545:8545"

  eigenlayer:
    platform: linux/amd64
    build:
      context: ./docker/eigenlayer
      dockerfile: Dockerfile.eigenlayer
    depends_on:
      - ethereum
    env_file:
      - .env
    volumes:
      - ./.eigenlayer:/root/.eigenlayer
  node1:
    image: opacitylabs/opacity-avs-node:local
    environment:
      - OPERATOR_BLS_KEY_PASSWORD=Testacc1Testacc1
      - OPERATOR_BLS_KEY_FILE=/.eigenlayer/operator_keys/testacc1.bls.key.json 
      - OPERATOR_ECDSA_KEY_FILE=/.eigenlayer/operator_keys/testacc1.ecdsa.key.json   
      - OPERATOR_ECDSA_KEY_PASSWORD=Testacc1Testacc1      
      - NODE_IP=http://node1:7047
    volumes:
      - ./.eigenlayer/operator_keys/testacc1.bls.key.json:/opacity-avs-node/config/opacity.bls.key.json
      - ./.eigenlayer/operator_keys/testacc1.ecdsa.key.json:/opacity-avs-node/config/opacity.ecdsa.key.json
      - ./docker/node/opacity.config.yaml:/opacity-avs-node/config/opacity.config.yaml
      - ./docker/node/config.yaml:/opacity-avs-node/config/config.yaml
      - ./docker/node/start.sh:/opacity-avs-node/start.sh
    ports:
      - "7047:7047"
    entrypoint: 
      - /bin/sh
      - -c
      - "chmod +x /opacity-avs-node/start.sh && /opacity-avs-node/start.sh"
    depends_on:
      eigenlayer: 
        condition: service_completed_successfully
  nodeselector:
    platform: linux/amd64
    image: opacitylabs/opacity-node-selector:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      eigenlayer:
        condition: service_completed_successfully
